app/models.py
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager,db

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    pic = db.Column(db.String(255))
    pass_secure = db.Column(db.String(255))
    profiles = db.relationship('Profile', backref = 'users', lazy = 'dynamic')
    blog = db.relationship('Blogs', backref = 'users', lazy = 'dynamic')
    comments = db.relationship('Comment', backref = 'users', lazy = 'dynamic')

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))    

    def __repr__(self):
        return f'User {self.username}'

class Profile(db.Model):
    __tablename__ = 'profiles'
    id = db.Column(db.Integer, primary_key = True)
    pic_path = db.Column(db.String())
    user = db.Column(db.Integer, db.ForeignKey("users.id"))        
    
class Blogs(db.Model):
    __tablename__ = 'blogers'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    texto = db.Column(db.String(255))
    comments = db.relationship('Comment', backref = 'blogers', lazy = 'dynamic')
    user = db.Column(db.Integer, db.ForeignKey('users.id'))

    def ububiko(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls):
        blogers = Blogs.query.all()
        return blogers

    def delete(self, id):
        comments = Comment.query.filter_by(id = id).all()
        for comment in comments:
            db.session.delete(comment)
            db.session.commit()
            db.session.delete(self)
            db.session.commit()

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(255))
    blogerss = db.Column(db.Integer,db.ForeignKey('blogers.id'))
    user = db.Column(db.Integer, db.ForeignKey('users.id'))
    @classmethod
    def get_comments(cls,blogerss):
        comments = Comment.query.filter_by(blogerss=blogerss).all()
        return comments

    def save_comme(self):
        db.session.add(self)
        db.session.commit() 

    def delete_comment(self):
        db.session.delete(self)
        db.session.commit()       

class Quotes:
    def __init__(self,quote,author):
        self.quote = quote
        self.author =  author 
        
class Subscribe(db.Model):
    __tablename__ = 'subscribe'
    id = db.Column(db.Integer,primary_key = True)
    email = db.Column(db.String(255))

    def sav_sub(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_sub(cls):
        subscribe = Subscribe.query.all()
        return subscribe



   

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField, ValidationError, BooleanField, TextAreaField, SelectField, RadioField
from wtforms.validators import Required
from ..models import User

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

class BlogsForm(FlaskForm):
    title = TextAreaField('Title')
    texto = TextAreaField('Blogs')
    submit = SubmitField()

class CommentsForm(FlaskForm):
    comments = TextAreaField('Comment')
    submit = SubmitField('Add Comment')  

class UpdateBlogForm(FlaskForm):
    title = StringField('Title',validators = [Required()])
    texto = TextAreaField('Blogs',validators = [Required()])
    submit = SubmitField('submit')      

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_uploads import UploadSet,configure_uploads,IMAGES


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

mail = Mail()

photos = UploadSet('photos', IMAGES)

def cree_app(config_name):

    app = Flask(__name__)

    app.config.from_object(config_options[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    mail.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .requests import configure_request
    configure_request(app)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for, abort
from . import main
from ..models import User,Blogs
from flask_login import login_required, current_user
from .forms import UpdateProfile,BlogsForm
from .. import db, photos
from .. requests import getQuotes

@main.route('/')
def index():
    blog = Blogs.get_blogs()
    isoko = getQuotes()

    return render_template('index.html',  blog = blog, isoko = isoko)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)
    
@main.route('/user/<uname>/update/pic', methods = ['POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)
    
    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname = user.username))
    
    return render_template('profile/update.html',form =form)
@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/add/blogers', methods=['GET','POST'])
@login_required
def inyandiko():
    
    form = BlogsForm()

    if form.validate_on_submit():
        title = form.title.data
        texto = form.texto.data
        inyandiko = Blogs(texto=texto, title=title)
        inyandiko.ububiko()

        return redirect(url_for('.index'))

    title = 'Blogs'
    return render_template('new_blog.html', blog_form = form,title=title)

@main.route('/blogers/<int:id>')
def bloger(id):
    bloge = Blogs.query.get(id)

    return render_template('index.html', bloge=bloge) 

@main.route('/comment/<int:id>',methods=['POST','GET'])
def comment(id):
    form=CommentForm()
    bloga = Blogs.query.get(id)
    commento = Comment.query.filter_by(id = id).all()
    if form.validate_on_submit():
        comment = form.comment.data
        blogerss = blogerss
        user = user
        newcomment = Comment(comment = comment,user = user,bloga = bloga)
        newcomment.save_comme()

    title = 'Comments'
    return redirect(url_for('.comment',blog_id = blog_id))
    return render_template('comment.html',form=form, title = title,bloga = bloga,commento=commento)     

@main.route('/deletecomment/<int:id>', methods = ['GET','POST'])
@login_required
def deletecomment(id):

    current_post = Comment.query.filter_by(id = id).first()

    if current_post.writer != current_user:
        abort(404)

    db.session.delete(current_post)
    db.session.commit()
    return redirect(url_for('.index'))
    return render_template('comment.html',current_post = current_post)

@main.route('/update/<int:id>',methods= ['GET','POST'])
@login_required
def updateblog(id):

    blogs = Blog.query.filter_by(id = id).first()
    if blogs is None:
        abort(404)

    form = UpdateBlogForm()

    if form.validate_on_submit():

        blogs.title = form.title.data
        blogs.content = form.content.data

        db.session.add(blogs)
        db.session.commit()

        return redirect(url_for('main.index'))
    return render_template('update_blog.html',form = form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comment.html
<h1>Comments</h1>
<form action="/blogers/{{blogers.id}}/comment" method="post">
    <div class="form-group">
        <input type="text" name="texto" class="form-control">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    </div>
</form>

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content %}
    <h1>Whooopss You are Done</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}

<style>
.hr{ 
  display: block;
  margin-left:200px;
  margin-right: 200px;
  border-style: inset;
  border-width: 1px;
} 
footer {
  /* position: fixed; */
  background-color:transparent;
  left: 0;
  bottom: 0;
  width: 100%;
  color:rgb(8, 8, 8);
  text-align: center;
  font-size: 10px;
}
#container{
    background-color: black;
    opacity:.8;
    color:#66a5a2;
}
</style>
<div class="container">
    <marquee behavior="inherit" direction="inherit"><h1 style="text-align:center;font-family: 'Berkshire Swash', cursive;color: rgb(76, 77, 80)">Blog Page</h1></marquee>
    <hr>                 
</div>
<div class="textmiddle" style="text-align:center;font-family: 'Berkshire Swash', cursive;">
    <h3 >Motivation Quote</h3>
    <p><i>{{ isoko.quote }}</i></p>
    <p>~ {{ isoko.author }} ~</p>
</div>    
<hr>
<div class="container" style="background-image:url(/static/photos/natures.jpg);background-repeat:no-repeat;width: 100%;height: 60%;">
    <br>
<div class="col-md-2">
        <h3 class="add-category"><a class="btn btn-primary" href="/add/blogers" style="background-color:#66a5a2; float:left;"><span aria-hidden="true"> Blog </span></a></h3>
</div>

<div class="col-md-5">
        <p style="font-size: 20px;">{{ macro.displayBlogsList(blog)}} </p>
</div>   
<div class="col-md-5">
        <div id="container" style="width:65%;height: 90%;">
                <h2 class="text-center">Subscribe</h2>
                <hr style="margin:20px;">
                <form>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" placeholder="Email" id="email" name="email" required>
                  </div>
                  <button type="submit" class="btn btn-success" style="background-color:#66a5a2; float: left;">Subscribe</button>
                </form>
              </div>
</div>
</div><br><br><br><br>
<div>
    <footer>
        <hr class="hr">
        <p>@2019 by ____Belie06Loryn.Proudly Created</p>
    </footer>
</div>
{% endblock %}

app/templates/macros.html
{% macro displayBlogsList(bloger_list) %}
  {% for bloger in bloger_list%}
      <div class="row">
          <div class="col-md-3">
          <div class="tab-content">
            
            <div class="container tab-pane active" id="all">
              <h3>{{bloger.title|upper}}</h3>
              <p>{{bloger.texto|upper}}</p>
              <a class="btn btn-primary" href="/update/" style="background-color:#66a5a2; float:left;"><span aria-hidden="true"> Update</span></a>
              <a class="btn btn-primary" href="/deletecomment/" style="background-color:#66a5a2; float:left;"><span aria-hidden="true"> Delete </span></a><br>
              <h3 class="add-category"><a class="btn btn-primary" href="/comment/" style="background-color:#66a5a2; float:left;"><span aria-hidden="true"> Comment </span></a></h3>
              {% for comment in comments %}
                <div class="panel panel-default">
                    <div class="panel-body">
                        <p>{{ comment.comment }}</p>
                    </div>
                </div>
              {% endfor %}  <br>
            </div>
          </div>
      </div>
      </div>
  {% endfor %}
{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"> Quotes </a>
            <a class="navbar-brand" href="/"> Blogs </a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li><a href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
        </ul>
    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro%}

{% block content %}
    <title> {{ title }} </title>

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-2"> </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">

                {{ wtf.quick_form(blog_form) }}

            </div>

        </div>
    </div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
  </div>
  <div class="col-md-4">
    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

      <input type="file"  name="photo" class="form-control" required>
      <input type="submit">
    </form>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}

app/templates/updateblog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% import 'macros.html' as macro%}

{% block content %}
    <title> {{ title }} </title>

    <div class="container">
        <div class="row">
            <div class="col-md-2 col-lg-2"> </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">

                {{ wtf.quick_form(form) }}

            </div>

        </div>
    </div>
{% endblock %}